### ISSUE TITLE
Colonists break down windows to get to jobs

### ISSUE THREAD

**Issue by DarcClan** [jptrrs/OpenTheWindows#11]
I'm having a new issue now since the latest update (I assume in regards to raiders now reacting to windows as doors) where my window keeps getting destroyed whenever a pawn thinks the path to something is easier by doing so. Attached is a screenshot showing the pawn breaking the window to mount a horse.
![20210428194839_1](https://user-images.githubusercontent.com/16677204/116486359-6d0d2380-a85b-11eb-9285-20da8f93a494.jpg)

**Comment by jptrrs** [comment]
Hi! Thanks for bringing this up. But I need a liiiitle bit more information to tackle this. It's all layed out here: https://steamcommunity.com/workshop/filedetails/discussion/1971860929/3345546435393929815/

**Comment by scyllaadell** [comment]
I can confirm that this is definitely a conflict with Giddy-Up! Ride and Roll. In summary: my colonists attempt to break through the basic Rustic window when they are trying to mount an animal to perform a job task. I can recreate it pretty easily by putting them in a base or room where leaving out the door would be more inconvenient for the pathing (like the door being on the opposite side of the animal pasture where the mounts hang out). 

I haven't tested this with other windows. I first noticed this on a medieval playthrough, but the log included only includes minimal mods as per your bug-hunting instructions (Harmony, Core, HugsLib, Mod Manager, Giddy-Up! Core, Giddy-Up! Ride and Roll, Open the Windows). I had the Royalty DLC disabled for this test. 

[HugsLib Log.txt](https://github.com/jptrrs/OpenTheWindows/files/6401559/HugsLib.Log.txt)

**Comment by jptrrs** [comment]
Thanks for reporting this!
I can confirm the issue. But it will take some more testing to pinpoint the cause. 
I didn't find it so easy to reproduce, so if anyone could provide a save where it will happen predictably that would be swell!
Also, did anyone experienced this with other windows than the rustic one?

**Comment by scyllaadell** [comment]
Here you go, I kept the save game that produced that error log: 

[WindowBugTest.zip](https://github.com/jptrrs/OpenTheWindows/files/6402983/WindowBugTest.zip)

**Comment by jptrrs** [comment]
Great, thanks!
