### ISSUE TITLE
Windows not acting as vents

### ISSUE THREAD

**Issue by CunninghamPatrick** [jptrrs/OpenTheWindows#12]
I noticed that none of the three windows I had in my colony's kitchen were affecting the temperatore of the kitchen (pretty much constantly 90-100F due to vanilla expanded stews cooking). I tried placing 4 windows in the kitchen, all with air flow allowed, and no change. It was as if it was not acting as a vent, so I confirmed it by going into god mode and placing a vent. Indeed, the vent worked; while the windows did not.

I further confirmed this by reducing my mods to _only_ open the windows, harmony, and hugslib. Using a steam geyser to test temperatures:

https://i.imgur.com/JBoD7bP.png
https://i.imgur.com/tAetDKe.png

Both pictures were taken after a few seconds of max speed to make sure the temperature was semi-stable. You can see that the one with the vent drastically reduces the temperature while the rustic window has no effect at all. Not pictured are my tests with all the other window types, and also with _no window or vent at all_, and the completely boxed in room with no door or window acted identical to a room with a window.

I can upload the save file if you would like, or obtain logs, but I figured this would be easy to reproduce. If it is not, I'll upload the save and grab some logs asap. :)

In an (likely) unrelated note: I noticed while going through your bug submitting guidelines that my mods version number is mismatched, as 2.0 is the newest version on steam, but mod manager reports my version number as 1.7.8; but I have features that were released in 2.0 such as the automatic ventilation toggle when outside comfortable temperatures (and I got the popup telling me about the update), so I think that may also be a minor bug? I can make an additional report on that if you prefer.

**Comment by CunninghamPatrick** [comment]
Just to confirm there was nothing wonky going on since my steam version number showed 1.7.8; I pulled the mo off github directly and confirmed it still exists.

**Comment by CunninghamPatrick** [comment]
I've done some more investigation (I have a lot of time on my hands as the school semester ends haha); and I think I've narrowed down the issue, though I am not skilled whatsoever at Rimworld modding, so I'm not 100% how to continue investigating.

After messing around and recompiling the mod, I was confused why my log messages in Building_Window:TickRare() were never being called, but I can get log messages to print on flicks from Building_Window:ReceiveCompSignal(). This leads me to think TickRare() is never being called? I've confirmed I can get messages inside Tick() and SpawnSetup(). I also confirmed the bug goes away if I move the temperature equalization logic into Tick() (though I'm sure that's horrible for performance, was just checking that TickRare was not being called).

Like I said, I'm very unfamiliar with Rimworld modding (it took me all day to figure out how to get the tooling setup just so I could build your mod haha), so I'm not sure what's wrong or why TickRare() is not being called but it does seem to be the case.

Hopefully this helps you. :)

**Comment by jptrrs** [comment]
BTW, don't bothet with that old verions number. It was a forgotten manifest feeding Mod Manager with lies.

**Comment by CunninghamPatrick** [comment]
No problem; I have too much time on my hands so it gave me a fun little project and a way to get a little more familiar with Rimworld modding. :)

**Comment by jptrrs** [comment]
Well, if you're learning, the bottomline here was: the tickerType defined
on the XML ThingDef is exclusive. That is: a "Rare" tickerType won't
trigger on a "Normal" tick, and vice-versa.
