### ISSUE TITLE
Cannot determine what side is exterior issue

### ISSUE THREAD

**Issue by pantherpusher** [jptrrs/OpenTheWindows#15]
It seems that my windows will randomly forget which side is outside and it's troublesome, I've made sure that the indoors is all roofed, and that there are no roofs on the outside, and yet it won't work and they swap which side is the interior at random

**Comment by jptrrs** [comment]
Thanks for reporting, but I'm going to need way more information than that! Check instructions here:
https://steamcommunity.com/workshop/filedetails/discussion/1971860929/3345546435393929815/
Thx!
