### ISSUE TITLE
Interaction with (flicking) windows can't be cancelled.

### ISSUE THREAD

**Issue by Xercaine** [jptrrs/OpenTheWindows#16]
Hello there! In the latest build, the command (either UI button or hotkey) to allow air or light through a window cannot be cancelled by pressing that button again, like most flickable items. Only way to reset the command is to make a colonist go through with whatever action was ordered.

I have not included a log file, as this bug doesn't seem to register any errors, and can be easily recreated on a new save game by starting a new game and placing down any window, then either toggling light or airflow.

This seems to happen to any window types (although not tested extensively), on new and old saves, and is not a mod conflict as it can be replicated with minimum mods enabled.

**Comment by jptrrs** [comment]
I'm assuming it was fixed.

**Comment by Xercaine** [comment]
Ahh, I did not consider that, thanks for pointing it out! Will try to do better in regards to that in the future. I noticed not long after I posted this that the issue seems to have been resolved, thanks for fixing it! Truly great mod and effort on your part!

**Comment by Xercaine** [comment]
Also sorry for not following up well on these, I'm almost never on Github so I only check up on it when I manage to remember to.

**Comment by jptrrs** [comment]
It's cool.
