### ISSUE TITLE
Manhunter pathfinding broken

### ISSUE THREAD

**Issue by JisPichi** [jptrrs/OpenTheWindows#17]
When a manhunting animal tries to target a pawn in a room with windows an error is sent and the animal instead wanders in place.

https://gist.github.com/ea9bd34ffd2f2cb9f0e2c9fa1f56e051
[BugExampleSave.zip](https://github.com/jptrrs/OpenTheWindows/files/6473610/BugExampleSave.zip)

**Comment by jptrrs** [comment]
Fixed & updated! Thanks for reporting and for that save file!! Made it very easy to debug.
