### ISSUE TITLE
Mod lag like hell.

### ISSUE THREAD

**Issue by Sergemenog** [jptrrs/OpenTheWindows#2]
I like idea of the mod, but when i have just one longhouse game already unplayable due lags.
![example](https://user-images.githubusercontent.com/38694499/74716811-123c6d00-5251-11ea-86a7-e637ae02b120.png)

**Comment by jptrrs** [comment]
That's a lot of unconnected windows!!! I'm assuming there's no roof over
them either, right? If so, you created a situation where there's more than
30 windows trying to figure out their orientation at the same time, and one
window area if affected by at least two other windows. Far from a normal
use case, don't you think?

João Pedro

**Comment by Sergemenog** [comment]
From player perspective any case that do not involve any form of cheating is normal. Mod description says nothing about what cause is normal and what is not. So i think if mod intended to work well only in several special cases which we call "normal" it should be disclaimed by big red letters in mod description.
Window have a roof above them by the way.
My suggestions for resolving the situation:
1) Define "normal" causes and disclaim possibility of heavy perfomance drop in mod description.
2) Fewer "figure out" per time unit, like 1 per 2-4 hour should do the thing.
3) Window detect when plased abnormaly and turn off part of their functionall, like beauty and light distribution.

**Comment by jptrrs** [comment]
"Mod description says nothing about what cause is normal and what is not."
- Well, now we can safely say 100% of people that take issue with that are
properly informed. :-)

João Pedro
