### ISSUE TITLE
Rotating east/west-facing windows' sprites according to their facing

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [jptrrs/OpenTheWindows#23]
Since you're already tracking window-facing, would it be possibly to rotate their sprite to match?

They look a little out-of-place, when placed on both the east *and* west sides of a room:

![image](https://user-images.githubusercontent.com/200/121931382-2723f600-cd09-11eb-8bc4-97973458b0fd.png)

**Comment by jptrrs** [comment]
In theory, yes, it is possible. But it would also create an inconsistent perspective.
