### ISSUE TITLE
Wrong text

### ISSUE THREAD

**Issue by RafaelDominiquini** [jptrrs/OpenTheWindows#3]
The text (hint) that indicates that I don't have material to make a bed is wrong (see the screenshot below).

![RimWorldWin64_c0Cv784SSP](https://user-images.githubusercontent.com/61922887/76696295-84457d80-6668-11ea-8100-3a5ba2ea7ed4.jpg)

Thanks

**Comment by jptrrs** [comment]
Oi Rafael! Esse texto tá assim faz tempo, várias pessoas já tinham me apontado o erro. Mas eu ainda não tinha encontrado exatamente a origem dele.. até agora. Já consertei e daqui a pouco subo pro Steam. Obrigado!

**Comment by RafaelDominiquini** [comment]
Ola. 
Mod errado mesmo, desculpa! Deveria ter aberto no https://github.com/jptrrs/SoftWarmBeds.
Obrigado!
