### ISSUE TITLE
Allow sight through windows

### ISSUE THREAD

**Issue by ZzZombo** [jptrrs/OpenTheWindows#5]
- If light is allowed to flow through, pawns should be able to see each other. Relevant for Prison Labor and its motivation system, for example.
- Additionally, if air flow is also allowed, pawns should be able to talk to each other.

**Comment by jptrrs** [comment]
I totally agree. But that would add a whole complexity layer to the code. Sorry, but it won't be possible.

**Comment by ZzZombo** [comment]
Sorry, what am I missing here? Can't they work like embrasures from mods when windows are open and like a wall otherwise?

**Comment by jptrrs** [comment]
As far as I know, windows work just like embrasures when they are open. Opening and closing the windows changes their "fillPercent" property (it's 1 when closed, just like the walls, and 0.65 when open, just like sandbags), the "CanBeSeenOver" game function, allowing enemies to target pawns behind windows, for instance, and the light-blocking tag for the ThingDef.
