### ISSUE TITLE
"Outdoors" need doesn't seem to be climbing when within range of a window?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [jptrrs/OpenTheWindows#6]
I'm trying to play my first mountain-base since installing OTW; but after many hours of play and planning my first mountain-base around the OpenTheWindows mechanic ...

![Screen Shot 2020-09-18 at 0 24 07](https://user-images.githubusercontent.com/200/93559626-cc11ce00-f945-11ea-8164-1c1105298ca8.png)

... I've belated realized that it doesn't actually seem to be ... working? Or rather, the "increased outdoors need" definitely is, but the "satisfy that need when standing near a window" doesn't seem to be.

For instance, this pawn checking out some art, is standing in range of a window:

<img width="907" alt="Screen Shot 2020-09-18 at 0 19 52" src="https://user-images.githubusercontent.com/200/93559648-df249e00-f945-11ea-8532-418b8157a581.png">
<img width="913" alt="Screen Shot 2020-09-18 at 0 20 02" src="https://user-images.githubusercontent.com/200/93559658-e350bb80-f945-11ea-8245-e33bba41720b.png">

... but his "Outdoors" need is staying still (yes, still image, but note the lack of a green-arrow indicating increasing fulfillment of the need):

<img width="1189" alt="Screen Shot 2020-09-18 at 0 20 29" src="https://user-images.githubusercontent.com/200/93559685-f6638b80-f945-11ea-96c5-b854a753860a.png">

Pretty much all of my colonists are "trapped underground" pretty much all of the time, despite designing my base specifically to allow them to stay "underground" near their windows most of the time! Did I do something wrong? Is this a bug?

**Comment by jptrrs** [comment]
Hi Elliot. Thanks for taking the time to take those images and explain what you're seeing (cool base, BTW!). 
You did not do anything wrong. The thing is the window area effect is kinda hard to visualize... or maybe I did a poor job of explaining how it works...
The windows **do not** fullfil outdoor needs, hence no green arrows. What they do is to prevent the need decay from being accelerated. In other words, pawns who are indoors and **out of window range** loose the outdoors 3x faster. You would have to compare the **speed** at what it decresases in front of a window and away from it. The only way to fullfil that need back is to actually be outdoors.

**Comment by ELLIOTTCABLE** [comment]
I see! Does this apply while sleeping? My first attempt above clearly prioritized sleeping-areas, but in retrospect, I'm guessing it's probably awake-time (workshops, etc) that should be outside-fronting?
