### ISSUE TITLE
Recursive beauty on overlapping windows

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [jptrrs/OpenTheWindows#7]
I don't have a screenshot handy; but it seems like windows whose view-area covers eachother *include* each one's beauty-total. In my previous colony, I had a Legendary-tier sculpture worth a few thousand beauty, in a small "courtyard" visible by several windows; but each of the windows could *also* see each of the others.

In the end, each window was providing ~25,000 beauty to the interior of the room it was facing. :P

**Comment by jptrrs** [comment]
Damn! That needs fixing! Added to my To-Do List.

**Comment by jptrrs** [comment]
Fixed!
