### ISSUE TITLE
Support for the slimmed-down "Just Glass" version of "Glass+Lights"

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [jptrrs/OpenTheWindows#8]
It'd be nice if the inter-mod integration supported the slimmed fork of Glass+Lights.

Original [comment](https://steamcommunity.com/sharedfiles/filedetails/comments/2045368641):

> Lumi MercuryDoll (Aug 9 @ 4:39am):
> Sadly doesn't seem to be inter-mod compatible like the original. Both Advanced Roofing and Open The Windows doesn't recognize this version of the mod.

**Comment by jptrrs** [comment]
Sooo.. yeah, if you meant Just Glass, that was solved long ago.
